language: generic
matrix:
  include:
    - os: linux
      env: CC=gcc-5 CXX=g++-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
    - os: linux
      env: CC=gcc-6 CXX=g++-6
      addons:
        apt:
          packages:
            - g++-6
          sources: *sources
    - os: linux
      env: CC=gcc-7 CXX=g++-7
      addons:
        apt:
          packages:
            - g++-7
          sources: *sources
    - os: linux
      env: CC=clang-3.8 CXX=clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
    - os: linux
      env: CC=clang-3.5 CXX=clang++-3.5
      addons:
        apt:
          packages:
            - clang-3.5
          sources:
            - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
    - os: osx
      osx_image: xcode8
      compiler: gcc
    - os: osx
      osx_image: xcode8
      compiler: clang

install: true

script:
  - cmake .
  - cmake --build .
